- hosts: local
  tasks:
    - name: Remove all existing containers (force)
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: true

    - name: Pull Docker image
      docker_image:
        name: inevertheless/spe_mini_calculator
        tag: latest
        source: pull

    - name: Run calculator container
      docker_container:
        name: calculator
        image: inevertheless/spe_mini_calculator:latest
        state: started
        detach: true
        restart_policy: no
        ports:
          - "8080:8080"  # map container port to host port
